from enum import Enum


class ResendError(str, Enum):
    FETCH_USER_FAILED = "FETCH_USER_FAILED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    ALREADY_VERIFIED = "ALREADY_VERIFIED"
    FETCH_RECORD_FAILED = "FETCH_RECORD_FAILED"
    NO_RECORD = "NO_RECORD"
    COOLDOWN = "COOLDOWN"
    SAVE_FAILED = "SAVE_FAILED"
    SEND_FAILED = "SEND_FAILED"
