from enum import Enum


class VerifyEmailError(str, Enum):
    FETCH_USER_FAILED = "FETCH_USER_FAILED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    ALREADY_VERIFIED = "ALREADY_VERIFIED"
    FETCH_RECORD_FAILED = "FETCH_RECORD_FAILED"
    NO_RECORD = "NO_RECORD"
    OTP_EXPIRED = "OTP_EXPIRED"
    MAX_ATTEMPTS = "MAX_ATTEMPTS"
    UPDATE_ATTEMPTS_FAILED = "UPDATE_ATTEMPTS_FAILED"
    INVALID_OTP = "INVALID_OTP"
    VERIFY_FAILED = "VERIFY_FAILED"
    TOKEN_FAILED = "TOKEN_FAILED"
